

@startuml

title ヘルプデスクサービスフロー

|User|
start
:質問を入力する;
:送信ボタンを押す;

|System|
:ユーザーの質問を受け取る;
:ユーザーの質問を分析し回答のための調査計画を作成する;
if (計画の作成に失敗した場合) then (yes)
    :エラーを表示する;
    stop
endif

:調査計画を実行する;
repeat
    repeat 
        if (対象が過去のQ&Aの場合) then (yes)
            :過去のQ&Aから関連する情報を検索する;
        else (対象がマニュアルの場合)
            :マニュアルから関連する情報を検索する;
        endif
        :調査結果をまとめる;
        :調査結果が目的を達成できているか確認する;
    repeat while (目的を達成するまでもしくは最大３回の調査を行うまで)
repeat while (計画がすべて完了するまで)

:すべての調査結果から回答を作成する;
:回答をユーザーに返す;

|User|
:回答を確認する;
stop

@enduml
